# Generated by Django 4.2.7 on 2023-11-28 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='price',
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='price',
        ),
        migrations.RemoveField(
            model_name='harddrive',
            name='price',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='price',
        ),
        migrations.RemoveField(
            model_name='manhinh',
            name='price',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='price',
        ),
        migrations.AlterField(
            model_name='discount',
            name='date_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 30, 13, 38, 15, 457403), null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='date_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 28, 13, 38, 15, 457403), null=True),
        ),
    ]
