# Generated by Django 4.2.7 on 2023-11-30 05:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_discount_date_end_alter_discount_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='date_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 2, 12, 35, 13, 99256), null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='date_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 30, 12, 35, 13, 99256), null=True),
        ),
    ]
