# Generated by Django 4.2.7 on 2023-11-30 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_feedback_product_alter_discount_date_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='vote',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='date_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 2, 13, 11, 39, 640355), null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='date_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 30, 13, 11, 39, 640355), null=True),
        ),
    ]
