# Generated by Django 4.2.7 on 2023-11-30 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_feedback_vote_alter_discount_date_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='subject',
        ),
        migrations.AlterField(
            model_name='discount',
            name='date_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 2, 14, 59, 8, 399497), null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='date_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 30, 14, 59, 8, 399497), null=True),
        ),
    ]
